/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login.store": [],
    "logout": [],
    "register.store": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "sanctum.csrf-cookie": [],
    "telescope": [
        {
            "name": "view",
            "required": false
        }
    ],
    "main": [],
    "admin": [],
    "category.index": [],
    "category.create": [],
    "category.store": [],
    "category.show": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "category.edit": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "category.update": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "category.destroy": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "login": [],
    "register": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
